name: omx_arm

x-runtime: &runtime
  build:
    context: ..
    dockerfile: docker/Dockerfile
    target: runtime
    args:
      ROS_DISTRO: jazzy
  image: ghcr.io/jcjcjc0705/omx_arm:latest
  network_mode: host
  ipc: host
  environment:
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

services:
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
      args:
        ROS_DISTRO: jazzy
    image: ghcr.io/jcjcjc0705/omx_arm:dev
    container_name: omx_dev

    stdin_open: true
    tty: true

    network_mode: host
    ipc: host

    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    devices:
      - /dev/serial/by-id/usb-ROBOTIS_OpenRB-150_1E22E703503059384C2E3120FF07180A-if00:/dev/omx_follower
      - /dev/serial/by-id/usb-ROBOTIS_OpenRB-150_01B5FC76503059384C2E3120FF083319-if00:/dev/omx_leader

    volumes:
      - ..:/ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    working_dir: /ws
    command: bash

  follower:
    <<: *runtime
    devices:
      - /dev/serial/by-id/usb-ROBOTIS_OpenRB-150_1E22E703503059384C2E3120FF07180A-if00:/dev/omx_follower
    command: ros2 launch omx_bringup omx_f.launch.py

  leader:
    <<: *runtime
    devices:
      - /dev/serial/by-id/usb-ROBOTIS_OpenRB-150_01B5FC76503059384C2E3120FF083319-if00:/dev/omx_leader
    command: ros2 launch omx_bringup omx_l.launch.py

  teleop:
    <<: *runtime
    depends_on: [follower, leader]
    command: ros2 launch omx_teleop omx_teleop.launch.py
